language: go
go:
  - '1.12'
  #- master
addons:
  ssh_known_hosts: github.com
install:
  - export TF_LOG=INFO
  - env GO111MODULE=on go mod vendor
script:
  - export GO111MODULE=on
  - TF_ACC=1 go test -v -cover
before_deploy:
  - export GO111MODULE=on
  - go get github.com/mitchellh/gox
  - export TARGET_OS="freebsd darwin linux windows"
  - export TARGET_ARCH="amd64"
  # Use terraform provider conventions
  #  https://www.terraform.io/docs/configuration/providers.html#third-party-plugins
  - export FILE_NAME="terraform-provider-elasticsearch_${TRAVIS_TAG}_{{.OS}}_{{.Arch}}"
  - gox -os "$TARGET_OS" -arch "$TARGET_ARCH" -output="$FILE_NAME"
  - CGO_ENABLED=0 gox -os "$TARGET_OS" -arch "$TARGET_ARCH" -output="${FILE_NAME}_static"
deploy:
  provider: releases
  api_key:
    secure: "$GITHUB_TOKEN"
  file: terraform-provider-ece*
  skip_cleanup: true
  file_glob: true
  on:
    tags: true
    branch: master
    go: '1.12'